# The region for the bucket.
aws_region: us-west-1

# The name of the destination bucket
aws_bucket: example

# The AWS access key and secret key to use for the backup.
aws_access_key_id: ${WEBSITE_BACKUP_AWS_ACCESS_KEY_ID}
aws_secret_access_key: ${WEBSITE_BACKUP_AWS_SECRET_ACCESS_KEY}

aws_retention:
  # Keep every backup for the first N days.
  keep_all_for_days: 2
  # After the above window, keep the latest backup of each day for N additional days.
  keep_latest_daily_for_days: 14
  # After the daily window, keep the latest backup of each month for N additional months.
  keep_latest_monthly_for_months: 12
  # After the monthly window, keep the latest backup of each year for N additional years.
  keep_latest_yearly_for_years: 3

# The filename of the backup object that will be created.  The current
# datetime will be appended.
object_name: example

# List of file/folder paths to include in the backup, preceed a path with ! to
# indicate the path should be excluded.  These may be absolute or relative to the
# app root.  If you are using a database handler, the dumpfile will be added to
# the manifest automatically for you.
manifest:
  - web/sites/*/files/
  - "!web/sites/*/files/styles/"
  - private/*/files/
  - "!private/*/files/tmp/"
  - web/sites/*/README.*

database:
  # The database connection URL to use when creating the database dump.
  #
  # This should be a standard connection string, for example:
  # mysql://user:password@host:3306/dbname
  #
  # In most cases, if your application already provides a DATABASE_URL
  # environment variable, you should reference it here as ${DATABASE_URL}.
  # Note that environment variables are only used when explicitly referenced in
  # this configuration file.
  url: ${DATABASE_URL}
  #
  # If your backup process needs to connect differently than the application
  # itself, you may define a separate environment variable instead, for example:
  # url: ${WEBSITE_BACKUP_DATABASE_URL}
  #
  # Note: if the password contains special characters such as @, :, /, ?, or #,
  # it should be URL-encoded.

  # Define which database export handler to use; one of: mysqldump.
  handler: mysqldump
  dumpfile: backup

  # To reduce the size of your dumpfile, you can specify any number of "cache
  # tables", or tables with ephemeral content that can be rebuilt by your
  # application. These cache_tables will have their STRUCTURE ONLY exported and
  # the contents of these tables will not exist in the dump file.
  cache_tables:
    - cache
    - cache_*
    - search_index
    - node_access
    - watchdog

encryption:
  password: ${WEBSITE_BACKUP_ENCRYPTION_PASSWORD}
  s3: true

directories:
  local: ../../private/backups

notifications:
  email:
    to:
      - ops@example.com
      - dev@example.com
    on_success:
      subject: Backup succeeded
    on_fail:
      subject: Backup failed
